config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    path('products', views.ProductListView.as_view(), name='product_list'),
    path('product', views.ProductDetailView.as_view(), name='product_detail')
]

core/models/user.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager
from django.core.mail import send_mail
from django.contrib.auth.models import (
    PermissionsMixin
)
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
import uuid
import os


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    Username and password are required. Other fields are optional.
    """
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True, blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    created_at = models.DateTimeField(_('created at'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

shop/models/product.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.

shop/views/product_detail_view.py
from django.shortcuts import render
from django.views.generic import TemplateView


class ProductDetailView(TemplateView):
    template_name = 'shop/product_detail.html'

shop/views/product_list_view.py
from django.shortcuts import render
from django.views.generic import TemplateView


class ProductListView(TemplateView):
    template_name = 'shop/product_list.html'

shop/views/top_view.py
from django.shortcuts import render
from django.views.generic import TemplateView


class TopView(TemplateView):
    template_name = 'shop/top.html'

templates/base/base.html
{% load static %}
{% load sass_tags %}

<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block meta_title %}{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}{% endblock %}" />
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Noto+Serif&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% sass_src 'sass/base/core.sass' %}">
{#	TODO OGP #}
{#	<meta property="og:url" content="ページURL" />#}
{#	<meta property="og:title" content="ページタイトル" />#}
{#	<meta property="og:type" content="ページタイプ" />#}
{#	<meta property="og:description" content="記事の抜粋文" />#}
{#	<meta property="og:image" content="画像URL" />#}
{#	<meta property="og:site_name" content="サイト名" />#}
{#	<meta property="og:local" content="ja_JP" />#}
{#	#}
{#	<!-- twitter card -->#}
{#	<meta name="twitter:card" content="カード種類" />#}
{#	<meta name="twitter:site" content="@Twitterユーザ名" />#}
{#	<meta name="twitter:description" content="抜粋文" />#}
{#	<meta name="twitter:title" content="ページタイトル" />#}
{#	<meta name="twitter:image" content="画像URL" />#}
{#	TODO amp対応等 #}
{#	<link rel="canonical" href="正規化するURL">#}
{#	TODO favicon #}
{#	<link rel="icon" href="./favicon.ico">#}
{#	<link rel="apple-touch-icon" sizes="180×180" href="./apple-touch-icon-180×180.png">#}
	{% block extrahead %}{% endblock %}
</head>
<body>
	{% block content %}{% endblock %}
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
	{% block extrajs %}{% endblock %}
</body>
</html>

templates/base/public_base.html
{% extends "base/base.html" %}

{% load static %}
{% load sass_tags %}

{% block extrahead %}
    <link rel="stylesheet" href="{% sass_src 'sass/base/public_base.sass' %}">
{% endblock %}

{% block content %}
	<header>
		<div class="fl aic">
			<h1 class="">EC Sample</h1>
			<nav class="mlauto">
				<ul class="nav fl">
					<li><a href="" class="nav_btn _login fl mr1">カート</a></li>
					<li><a href="" class="nav_btn _login fl mr1">ログイン</a></li>
				</ul>
			</nav>
		</div>
	</header>
{% endblock %}

{% block extrajs %}
{% endblock %}

templates/mod/ajax_setup.html
<script>
	function getCookie(name) {
		var cookieValue = null;
		if (document.cookie && document.cookie !== '') {
			var cookies = document.cookie.split(';');
			for (var i = 0; i < cookies.length; i++) {
				var cookie = jQuery.trim(cookies[i]);
				// Does this cookie string begin with the name we want?
				if (cookie.substring(0, name.length + 1) === (name + '=')) {
					cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
					break;
				}
			}
		}
		return cookieValue;
	}
	var csrftoken = getCookie('csrftoken');
	function csrfSafeMethod(method) {
		// these HTTP methods do not require CSRF protection
		return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
	}
	$.ajaxSetup({
		beforeSend: function (xhr, settings) {
			if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
				xhr.setRequestHeader("X-CSRFToken", csrftoken);
			}
		}
	});
</script>

templates/mod/toastr.css.html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

templates/mod/toastr.js.html
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

templates/mod/toastr_full_width.js.html
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script>
	$(function() {
		toastr.options = {
			"closeButton": false,
			"debug": false,
			"newestOnTop": false,
			"progressBar": false,
			"positionClass": "toast-top-full-width",
			"preventDuplicates": false,
			"onclick": null,
			"showDuration": "300",
			"hideDuration": "1000",
			"timeOut": "5000",
			"extendedTimeOut": "1000",
			"showEasing": "swing",
			"hideEasing": "linear",
			"showMethod": "fadeIn",
			"hideMethod": "fadeOut"
		}
	})
</script>

templates/shop/product_detail.html
{% extends 'base/public_base.html' %}

{% load static %}
{% load sass_tags %}

{% block meta_title %}Product Detail Page | EC Sample{% endblock %}
{% block meta_description %}{% endblock %}

{% block extrahead %}
	{{ block.super }}
    <link rel="stylesheet" href="{% sass_src 'sass/shop/product_detail.sass' %}">
{% endblock %}

{% block content%}
    {{ block.super }}
    <main id="main" class="pt3 pb5">
        <div class="content _wr">
            <div class="fl">
                <div class="img _wr"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                <div class="fl cl w100">
                    <div class="prod _meta pl2 pr2">
                        <h2 class="prod _title">Product Name</h2>
                        <div class="prod _description">商品説明欄</div>
                    </div>
                    <div class="tocart _wr pl2 pr2 pt2 pb2">
                        <a class="tocart _btn fl jcc">カートに入れる</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block extrajs %}
{% endblock %}

templates/shop/product_list.html
{% extends 'base/public_base.html' %}

{% load static %}
{% load sass_tags %}

{% block meta_title %}Product List Page | EC Sample{% endblock %}
{% block meta_description %}{% endblock %}

{% block extrahead %}
	{{ block.super }}
    <link rel="stylesheet" href="{% sass_src 'sass/shop/product_list.sass' %}">
{% endblock %}

{% block content%}
    {{ block.super }}
    <main id="main" class="pt3 pb5">
        <h2 class="title fl jcc aic">Category Name</h2>
        <div class="content _wr pt3 gr">
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>
            <div class="fl jcc">
                <a href="{% url 'shop:product_detail' %}" class="prod _wr fl cl">
                    <div class="img _wr fl aic jcc"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div>
                    <div class="meta _wr"><h3 class="prod _title">product name</h3><div class="prod _price">￥2000</div></div>
                </a>
            </div>

        </div>
    </main>
{% endblock %}

{% block extrajs %}
{% endblock %}

templates/shop/top.html
{% extends 'base/public_base.html' %}

{% load static %}
{% load sass_tags %}

{% block meta_title %}EC Sample{% endblock %}
{% block meta_description %}{% endblock %}

{% block extrahead %}
	{{ block.super }}
    <link rel="stylesheet" href="{% sass_src 'sass/shop/top.sass' %}">
{% endblock %}


{% block content %}
	{{ block.super }}
	<main id="main" class="pt5 pb5">
{#		<div class="heading _wr">#}
{##}
{#		</div>#}
		<div class="content _wr">
			<h2 class="content _title fl jcc aic mb3">category 1</h2>
			<div class="prod gr">
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
			</div>
			<div class="more _link"><a href="{% url 'shop:product_list' %}" class="more _a">...view more</a></div>
		</div>
		<div class="content _wr">
			<h2 class="content _title fl jcc aic mb3">category 2</h2>
			<div class="prod gr">
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
			</div>
			<div class="more _link"><a href="{% url 'shop:product_list' %}" class="more _a">...view more</a></div>
		</div>
		<div class="content _wr">
			<h2 class="content _title fl jcc aic mb3">category 3</h2>
			<div class="prod gr">
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
				<a href="{% url 'shop:product_detail' %}" class="prod _el fl cl jcc aic pb2"><div class="prod _img fl aic"><img src="http://placehold.jp/250x150.png?text=Sample Image"></div><div class="prod _title">product name</div></a>
			</div>
			<div class="more _link"><a href="{% url 'shop:product_list' %}" class="more _a">...view more</a></div>
		</div>
	</main>
{% endblock %}


{% block extrajs %}
	{{ block.super }}
{% endblock %}